### ISSUE TITLE
请求提供apk的源代码

### ISSUE THREAD

**Issue by MasterOfStar** [liuran001/GJZS-old#1]
请求提供搞机助手重置版apk的源代码

**Comment by liuran001** [comment]
使用原版反编译得到，没有源代码 ~~（我不会写代码）~~

**Comment by MasterOfStar** [comment]
😂😂😂好吧
不过提醒一下，pio前几天改license了，现在是GPLv3了，要求发布二进制同时必须发布源代码（或者反编译后未打包的文件）
不然可能涉及不遵循开源许可😂😂😂
这个需要注意一下

**Comment by liuran001** [comment]
> 😂😂😂好吧
> 不过提醒一下，pio前几天改license了，现在是GPLv3了，要求发布二进制同时必须发布源代码（或者反编译后未打包的文件）
> 不然可能涉及不遵循开源许可😂😂😂
> 这个需要注意一下

@MasterOfStar 感谢提醒
（未打包的文件也可以吗，那我直接把apk解包传上来得了🌝）

**Comment by MasterOfStar** [comment]
> > 😂😂😂好吧
> > 不过提醒一下，pio前几天改license了，现在是GPLv3了，要求发布二进制同时必须发布源代码（或者反编译后未打包的文件）
> > 不然可能涉及不遵循开源许可😂😂😂
> > 这个需要注意一下
> 
> @MasterOfStar 感谢提醒
> （未打包的文件也可以吗，那我直接把apk解包传上来得了🌝）

根据GPLv3来讲应该是可以的
>作品的源码指其可修改的首选形式 
来自[中文非正式翻译](https://jxself.org/translations/gpl-3.zh.shtml)
所以未打包的文件应该也算作源码
不过记得给repo加一个GPLv3的License

**Comment by liuran001** [comment]
> > > 😂😂😂好吧
> > > 不过提醒一下，pio前几天改license了，现在是GPLv3了，要求发布二进制同时必须发布源代码（或者反编译后未打包的文件）
> > > 不然可能涉及不遵循开源许可😂😂😂
> > > 这个需要注意一下
> > 
> > 
> > @MasterOfStar 感谢提醒
> > （未打包的文件也可以吗，那我直接把apk解包传上来得了🌝）
> 
> 根据GPLv3来讲应该是可以的
> 
> > 作品的源码指其可修改的首选形式
> > 来自[中文非正式翻译](https://jxself.org/translations/gpl-3.zh.shtml)
> > 所以未打包的文件应该也算作源码
> > 不过记得给repo加一个GPLv3的License

@MasterOfStar 已经正式添加GPLv3许可证
